[package]
name = "learning_rust"
version = "0.1.0"
authors = ["Marcel Jackisch <jackisch@protonmail.com>"]
edition = "2018"


[dependencies]
hello_macro = { path = "./hello_macro" }
hello_macro_derive = { path = "./hello_macro/hello_macro_derive" }